import Common
import HotKey

let dvorakMap: [String: Key] = keyNotationToKeyCode + [
    leftSquareBracket: .minus,
    rightSquareBracket: .equal,

    quote: .q,
    comma: .w,
    period: .e,
    p: .r,
    y: .t,
    f: .y,
    g: .u,
    c: .i,
    r: .o,
    l: .p,
    slash: .leftBracket,
    equal: .rightBracket,
    backslash: .backslash,

    a: .a,
    o: .s,
    e: .d,
    u: .f,
    i: .g,
    d: .h,
    h: .j,
    t: .k,
    n: .l,
    s: .semicolon,
    minus: .quote,

    semicolon: .z,
    q: .x,
    j: .c,
    k: .v,
    x: .b,
    b: .n,
    m: .m,
    w: .comma,
    v: .period,
    z: .slash,
]

let colemakMap: [String: Key] = keyNotationToKeyCode + [
    q: .q,
    w: .w,
    f: .e,
    p: .r,
    g: .t,
    j: .y,
    l: .u,
    u: .i,
    y: .o,
    semicolon: .p,
    leftSquareBracket: .leftBracket,
    rightSquareBracket: .rightBracket,
    backslash: .backslash,

    a: .a,
    r: .s,
    s: .d,
    t: .f,
    d: .g,
    h: .h,
    n: .j,
    e: .k,
    i: .l,
    o: .semicolon,
    quote: .quote,

    z: .z,
    x: .x,
    c: .c,
    v: .v,
    b: .b,
    k: .n,
    m: .m,
    comma: .comma,
    period: .period,
    slash: .slash,
]
